import os

from map import GAME_MAP


SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
DISPLAY = (SCREEN_WIDTH, SCREEN_HEIGHT)

HW = SCREEN_WIDTH // 2

OFFSET_X = 0
OFFSET_Y = -250

BACGROUND_COLOR = (0,0,0)

WIDTH_HERO = 69
HEIGHT_HERO = 55

BLOCK_WIDTH = 80
BLOCK_HEIGHT = 40

FILE_DIR = os.path.dirname(__file__)
SCREEN_START = (0,0)

FRAME_DELAY_RUN = 150
FPS = 60
JUMP_SPEED = 3
JUMP_COUNTER_DEFAULT = 50
GRAVITY_SPEED = 3
SPEED = 2

REAL_WIDTH = 80 * len(GAME_MAP[0]) - SCREEN_WIDTH
