STANDING_HERO = 'images/heroes/fat_hero.png'
RUN_HERO_1 = 'images/heroes/fat_hero_run.png'
RUN_HERO_2 = 'images/heroes/fat_hero_run_1.png'
JUMP_HERO = 'images/heroes/fat_hero_jump.png'
STANDING_SKINNY_HERO = 'images/heroes/skinny_hero.png'
RUN_SKINNY_HERO_1 = 'images/heroes/skinny_hero_run.png'
RUN_SKINNY_HERO_2 = 'images/heroes/skinny_hero_run_1.png'
JUMP_SKINNY_HERO = 'images/heroes/skinny_hero_jump.png'

BLOCK = 'images/bg/block.png'
